### PR TITLE
8 downgrade

### PR DESCRIPTION
**Pull request by tcburns24**
**Checkpoint**: 8
**Description**: User can upgrade to premium, then downgrade back to standard. Price reverted to $19.99 after discovering the `amount:` field in `Stripe::Charge:create(` operates in cents not dollars.
**Test Coverage**: 92.77%

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@tcburns24 this branch has conflicts that must be resolved. Is it possible you don't have the master changes? Either way, please work through Github's instructions. Let me know if you need help!

**Comment by tcburns24** [comment]
Hi @wonderwoman13, I just made an attempt at fixing the conflicts -- how can I check my work? I'm hoping that the "resolve branch conflicts" commit will resolve the issue, but I'm not sure if that did the trick or not. Thanks!

**Comment by brittanyjspringer** [comment]
@tcburns24 unfortunately, these files still need help. 

app/assets/stylesheets/users.scss
app/controllers/charges_controller.rb
app/views/charges/_new_charge.html.erb
app/views/users/show.html.erb
config/routes.rb
coverage/.resultset.json
coverage/index.html

Please do the following: 

Step 1: From your project repository, bring in the changes and test.

git fetch origin
git checkout -b 8-downgrade origin/8-downgrade
git merge master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff 8-downgrade
git push origin master

**Comment by tcburns24** [comment]
@wonderwoman13 Ok, I think I'm in the clear now :-)

**Comment by brittanyjspringer** [comment]
@tcburns24 not quite. I still see: 

# <<<<<<< HEAD


throughout your files. Click on "Files changed" above to see what I see.

**Comment by tcburns24** [comment]
@wonderwoman13 Oh I see. Can I solve this by repeating the steps on the command line? Or manually deleting the **<<<<<< HEAD** text?

**Comment by brittanyjspringer** [comment]
Manually deleting, please!

**Comment by tcburns24** [comment]
@wonderwoman13 Ok, that should do it!

**Review by brittanyjspringer — COMMENTED** [review]
My name is Brittany Martin and I approve this PR.

**Pull request merged**
