### PR TITLE
5-roles 1st attempt

### PR DESCRIPTION
**Pull request by tcburns24**
Hi Brittany, 

I read through the **Pundit** documentation and have a basic understanding. I'm hoping to make a little more headway on checkpoint 5 before our Monday appointment, so I've pushed this commit up with a few questions. 

I'm hoping that my `wiki_policy.rb` file is approaching correct; I know it's bare-bones at the moment, but is it structurally on the right track?. A few questions about Pundit:

1) Which actions should I list on `wiki_policy.rb`? All those available to each role (default, admin, and premium)? Or only the ones specific to non-default users (admin and premium)?

2) Will I need `user_policy.rb`?

3) It seems like I'll need a `PostsController` soon, yes? Posts would `belong_to :wikis` and wikis should `have_many :posts`, right? If I'm correct so far, I feel like I should create those files before setting policies for them.

Thanks! This checkpoint is a good challenge for me :-)

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
Hey @tcburns24 --
1. Yes, your setup for wiki_policy looks correct so far. You should list all CRUD actions and use the logic of what role the user has AND if they are the user that created the wiki AND if the wiki is private. I suggest sketching these scenarios down on a spreadsheet or paper. 
2. Not user_policy.rb -- Devise has you handled. 
3. No Posts are needed in this project. A Wiki, in theory, is another name for a Post. We will end up with a Collaborator model, but not until later. In the end, the only policy you will have is for Application and Wiki. 

Back to you!

Britt

**Comment by tcburns24** [comment]
Thanks for this -- I've got a clearer picture now, but here's my next question:

I took your advice and jotted down which CRUD actions should be available to which user roles (Standards, Admins, and Premiums). Some actions are available to all 3 roles, and others only to the wiki's owner. 

1) Am I correct so far in distributing the CRUD actions?
2) How do I indicate that an action is available only to the wiki's owner. (I looked through Bloccit in search of an answer, but no luck. I'm guessing I'll need the `current_user` and/or `sign_in @user` to do this...?)

**AVAILABLE CRUD ACTIONS:**
**Create**: All 3
**Edit**: Admin, wiki owner
**New**: All 3
**Index**: All 3
**Show**: All 3
**Update**: Admin, wiki owner
**Delete**: Admin, wiki owner

Hope I'm on the right track, thanks!

**Comment by brittanyjspringer** [comment]
@tcburns24 the available CRUD actions are all correct -- good job!

wiki.user will get you the user :)

**Comment by brittanyjspringer** [comment]
@tcburns24 I just committed with the following: 

The tense of wikis and wiki was mixed up on authorize methods in the controller. Index needed to be "wikis" and Show needed to be "wiki". I also fixed the index view since it was looking for wiki.description, not body. I also added an email to the Stranger User in tests since for some reason, Faker was not creating a unique email for them. 

You currently have 6 failing tests due to the authorizations rules changing. Please work through them and don't forget to do a $ git pull origin 5-rules before you start working.

**Comment by tcburns24** [comment]
@wonderwoman13 , thank you for all your help here. I managed to pass those 6 failing tests by changing my WikiPolicy's`def destroy?` method from `user.is_admin? || wiki.user == user` to `true`. Although this passes my tests, I'm not sure it's the solution I want considering anyone can delete wikis...right? I'm guessing those 6 failing tests were related to @stranger_user?

Should I leave my WikiPolicy's `def delete?` action as is? Or refactor it?

Thanks!

p.s. Faker's Hipster sentences are hilarious! I was cracking up at my desk reading them off the terminal failed tests text :-D

**Comment by brittanyjspringer** [comment]
Hi @tcburns24 --

Those tests should fail :) You need to change the tests to expect a unauthorized redirect like Bloccit does with standard users. 👍 Basically, the failure logs are telling you what you should be expecting. 

Being a hipster is hard work!

Cheers,

Britt

**Comment by tcburns24** [comment]
I see. In my wikis_controller_spec.rb file I already have:

```
 it "deletes the wiki" do
    delete :destroy, {id: @my_wiki.id}
    count = Wiki.where({id: @my_wiki.id}).size
    expect(count).to eq 0
  end

  it "redirects to wiki index" do
    delete :destroy, {id: @my_wiki.id}
    expect(response).to redirect_to wikis_path
  end
```

Do I need to edit these tests? Thanks!

**Comment by brittanyjspringer** [comment]
@tcburns24 Likely yes. Please paste the failures messages for these two, unless they are passing.

**Comment by tcburns24** [comment]
Here are the failure messages:

rspec ./spec/controllers/wikis_controller_spec.rb:125 # WikisController standard DELETE destroy deletes the wiki

rspec ./spec/controllers/wikis_controller_spec.rb:131 # WikisController standard DELETE destroy redirects to wiki index

rspec ./spec/controllers/wikis_controller_spec.rb:250 # WikisController admin DELETE destroy deletes the wiki

rspec ./spec/controllers/wikis_controller_spec.rb:256 # WikisController admin DELETE destroy redirects to wiki index

rspec ./spec/controllers/wikis_controller_spec.rb:374 # WikisController premium DELETE destroy deletes the wiki

rspec ./spec/controllers/wikis_controller_spec.rb:380 # WikisController premium DELETE destroy redirects to wiki index

**Comment by brittanyjspringer** [comment]
Hey @tcburns24 - I meant the failure messages where it says: 

Expected yada
Got boing

Likely, your tests need to be changes to the "got" vs. the "expected". Happy to review tonight.

**Comment by tcburns24** [comment]
**Checkpoint**: 5
**Description**: Pundit errors solved, all tests pass
**Test Coverage**: 93.75%

**Pull request merged**
